---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sql
  myapache:
    image: httpd
    ports:
      - 9999:80
    links:
      - mydb:mysql
  myphp:
    image: php:7.2-apache
    links:
      - myapache:myhttpd
      - mydb:mysql

...